In [1]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

In [3]:
milk = pd.read_csv("milk.csv",
                   index_col=0)
milk

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [5]:
# Create scaler: scaler
scaler = StandardScaler()
milkscaled=scaler.fit_transform(milk)
milkscaled

array([[ 0.94880628, -1.00929078, -0.90320785,  1.54221661, -1.03755398],
       [ 0.82140698, -1.34460333, -0.66061872,  1.04077335, -1.25994474],
       [ 0.81344452, -1.12106163, -0.73824724,  1.26363702, -1.38124879],
       [ 0.96473119, -1.26077519, -0.86439359,  1.15220518, -0.93646727],
       [ 0.97269365, -1.56814503, -0.56358307,  0.14931866, -1.54298752],
       [ 0.75770733, -0.75780637, -0.67032229,  0.37218233, -0.30972968],
       [ 0.69400768, -0.3945511 , -0.83528289,  0.87362559,  0.07439982],
       [ 0.31180978, -0.08718126, -0.23366185,  0.31646641, -0.16820828],
       [ 0.29588487,  0.33195943, -0.30158681, -0.79785195, -0.02668689],
       [ 0.2719975 ,  1.08641267, -0.38891889,  0.14931866, -0.22886031],
       [ 0.2719975 ,  0.10841772, -0.42773316,  0.42789825,  0.13505184],
       [ 0.66215786, -0.64603552, -0.68972942,  0.81790968, -0.1277736 ],
       [ 0.94084382, -1.17694705, -0.82557933,  0.76219376, -0.79494588],
       [ 0.36754698,  0.24813129, -0.50536168, -0.24069277,  0.47874665],
       [ 0.63827049, -0.89751993, -0.53447237,  0.65076192, -0.32994702],
       [ 0.30384733, -0.1710094 , -0.37921533,  0.31646641,  0.09461716],
       [-0.15001267,  0.86287096, -0.07840481, -0.63070419,  0.68092007],
       [-0.59591022, -0.72986365,  0.70758398,  0.81790968, -0.47146841],
       [-0.54813548,  1.70115234,  0.27092354, -1.24357929,  2.90482766],
       [-0.45258601,  0.83492825,  0.22240572, -0.46355644,  1.08526691],
       [-0.97810812,  1.1702408 ,  0.91135885, -0.85356786,  1.08526691],
       [-1.06569514,  1.25406894,  0.96958024, -0.90928378,  1.08526691],
       [-1.06569514,  1.36583979,  1.05691232, -1.41072704,  1.69178716],
       [-2.53078707,  0.97464182,  3.07525389, -2.30218173, -0.02668689],
       [-2.65022392,  1.22612623,  2.38630076, -1.80073847, -0.67364183]])

In [7]:
milkscaled = pd.DataFrame(milkscaled,
                          columns=milk.columns,
                          index=milk.index)
milkscaled

               water   protein       fat   lactose       ash
Animal
HORSE       0.948806 -1.009291 -0.903208  1.542217 -1.037554
ORANGUTAN   0.821407 -1.344603 -0.660619  1.040773 -1.259945
MONKEY      0.813445 -1.121062 -0.738247  1.263637 -1.381249
DONKEY      0.964731 -1.260775 -0.864394  1.152205 -0.936467
HIPPO       0.972694 -1.568145 -0.563583  0.149319 -1.542988
CAMEL       0.757707 -0.757806 -0.670322  0.372182 -0.309730
BISON       0.694008 -0.394551 -0.835283  0.873626  0.074400
BUFFALO     0.311810 -0.087181 -0.233662  0.316466 -0.168208
GUINEA PIG  0.295885  0.331959 -0.301587 -0.797852 -0.026687
CAT         0.271998  1.086413 -0.388919  0.149319 -0.228860
FOX         0.271998  0.108418 -0.427733  0.427898  0.135052
LLAMA       0.662158 -0.646036 -0.689729  0.817910 -0.127774
MULE        0.940844 -1.176947 -0.825579  0.762194 -0.794946
PIG         0.367547  0.248131 -0.505362 -0.240693  0.478747
ZEBRA       0.638270 -0.897520 -0.534472  0.650762 -0.329947
SHEEP       0.303847 -0.171009 -0.379215  0.316466  0.094617
DOG        -0.150013  0.862871 -0.078405 -0.630704  0.680920
ELEPHANT   -0.595910 -0.729864  0.707584  0.817910 -0.471468
RABBIT     -0.548135  1.701152  0.270924 -1.243579  2.904828
RAT        -0.452586  0.834928  0.222406 -0.463556  1.085267
DEER       -0.978108  1.170241  0.911359 -0.853568  1.085267
REINDEER   -1.065695  1.254069  0.969580 -0.909284  1.085267
WHALE      -1.065695  1.365840  1.056912 -1.410727  1.691787
SEAL       -2.530787  0.974642  3.075254 -2.302182 -0.026687
DOLPHIN    -2.650224  1.226126  2.386301 -1.800738 -0.673642

In [8]:
# Create a KMeans instance with clusters: model
model = KMeans(n_clusters=3,random_state=2021)

In [9]:
# Fit model to points
model.fit(milkscaled)

KMeans(n_clusters=3, random_state=2021)

In [10]:
# Cluster Centroids
print(model.cluster_centers_)

[[-0.71003876  1.19818352  0.55879598 -0.91856977  1.4222226 ]
 [ 0.55536727 -0.55234524 -0.51849003  0.56554934 -0.46076511]
 [-2.5905055   1.10038402  2.73077733 -2.0514601  -0.35016436]]

In [11]:
#model.n_init
# Determine the cluster labels of new_points: labels
labels = model.predict(milkscaled)

In [12]:
# Print cluster labels of new_points
print(labels)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 2 2]

In [14]:
clusterID = pd.DataFrame({'ClustID':labels},index=milk.index)
clusteredData = pd.concat([milk,clusterID],
                          axis='columns')
clusteredData

            water  protein   fat  lactose   ash  ClustID
Animal
HORSE        90.1      2.6   1.0      6.9  0.35        1
ORANGUTAN    88.5      1.4   3.5      6.0  0.24        1
MONKEY       88.4      2.2   2.7      6.4  0.18        1
DONKEY       90.3      1.7   1.4      6.2  0.40        1
HIPPO        90.4      0.6   4.5      4.4  0.10        1
CAMEL        87.7      3.5   3.4      4.8  0.71        1
BISON        86.9      4.8   1.7      5.7  0.90        1
BUFFALO      82.1      5.9   7.9      4.7  0.78        1
GUINEA PIG   81.9      7.4   7.2      2.7  0.85        1
CAT          81.6     10.1   6.3      4.4  0.75        1
FOX          81.6      6.6   5.9      4.9  0.93        1
LLAMA        86.5      3.9   3.2      5.6  0.80        1
MULE         90.0      2.0   1.8      5.5  0.47        1
PIG          82.8      7.1   5.1      3.7  1.10        1
ZEBRA        86.2      3.0   4.8      5.3  0.70        1
SHEEP        82.0      5.6   6.4      4.7  0.91        1
DOG          76.3      9.3   9.5      3.0  1.20        0
ELEPHANT     70.7      3.6  17.6      5.6  0.63        1
RABBIT       71.3     12.3  13.1      1.9  2.30        0
RAT          72.5      9.2  12.6      3.3  1.40        0
DEER         65.9     10.4  19.7      2.6  1.40        0
REINDEER     64.8     10.7  20.3      2.5  1.40        0
WHALE        64.8     11.1  21.2      1.6  1.70        0
SEAL         46.4      9.7  42.0      0.0  0.85        2
DOLPHIN      44.9     10.6  34.9      0.9  0.53        2

In [15]:
clusteredData.groupby('ClustID').mean() Simran.Awati@infinite.com
clusteredData.sort_values('ClustID')

            water  protein   fat  lactose   ash  ClustID
Animal
WHALE        64.8     11.1  21.2      1.6  1.70        0
REINDEER     64.8     10.7  20.3      2.5  1.40        0
DEER         65.9     10.4  19.7      2.6  1.40        0
RAT          72.5      9.2  12.6      3.3  1.40        0
RABBIT       71.3     12.3  13.1      1.9  2.30        0
DOG          76.3      9.3   9.5      3.0  1.20        0
HORSE        90.1      2.6   1.0      6.9  0.35        1
ELEPHANT     70.7      3.6  17.6      5.6  0.63        1
SHEEP        82.0      5.6   6.4      4.7  0.91        1
ZEBRA        86.2      3.0   4.8      5.3  0.70        1
PIG          82.8      7.1   5.1      3.7  1.10        1
MULE         90.0      2.0   1.8      5.5  0.47        1
FOX          81.6      6.6   5.9      4.9  0.93        1
CAT          81.6     10.1   6.3      4.4  0.75        1
GUINEA PIG   81.9      7.4   7.2      2.7  0.85        1
BUFFALO      82.1      5.9   7.9      4.7  0.78        1
BISON        86.9      4.8   1.7      5.7  0.90        1
CAMEL        87.7      3.5   3.4      4.8  0.71        1
HIPPO        90.4      0.6   4.5      4.4  0.10        1
DONKEY       90.3      1.7   1.4      6.2  0.40        1
MONKEY       88.4      2.2   2.7      6.4  0.18        1
ORANGUTAN    88.5      1.4   3.5      6.0  0.24        1
LLAMA        86.5      3.9   3.2      5.6  0.80        1
SEAL         46.4      9.7  42.0      0.0  0.85        2
DOLPHIN      44.9     10.6  34.9      0.9  0.53        2